Create generic exception handler
nelfan/BORDA pull request #35
Opened 2021-05-31 11:25 UTC by ChernykhVyacheslav

Created generic exception handlerf or CustomEntityNotFoundException and CustomFailedToDeleteEntityException

https://trello.com/c/65HgbOCw/145-create-generic-exception-handler

2021-05-31 11:55 UTC, achehrynets requested changes
Requested changes.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardController.java
> +                boardService.createOrUpdate(board),
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardController.java
> +                boardService.createOrUpdate(existingBoard),
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardController.java
> +                        .stream().map(boardList -> modelMapper.map(boardList,
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardController.java
> +                                boardService.getBoardById(boardId), boardList),
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardListController.java
> +                        boardListService.getBoardListById(boardListId),
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardListController.java
> +                        boardListService.createOrUpdate(existingBoardList),
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardListController.java
> +                boardListService.getAllTicketsByBoardListId(boardListId)
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardListController.java
> +                        boardListService.addTicketToBoardList(
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardListController.java
> +                        boardListService.deleteTicketFromBoardList(
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/BoardListController.java
> +                modelMapper.map(
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/UserController.java
> +                .map(user -> modelMapper.map(user, UserSimpleDTO.class))
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/UserController.java
> +                userService.createOrUpdate(user),
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/UserController.java
> +                jwtConvertor.getUserByJWT(authorization),
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/UserController.java
> +                userService.createOrUpdate(existingUser),
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/UserController.java
> +                jwtConvertor.getUserByJWT(authorization))
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/UserController.java
> +                userService.getBoardsByUserAndBoardRoleId(
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/UserController.java
> +                userService.getAllCommentsByUser(jwtConvertor.getUserByJWT(authorization))
Don't write logic in a single row.

2021-05-31 11:55 UTC, achehrynets commented on shared/src/main/java/com/softserve/borda/config/RestResponseEntityExceptionHandler.java
> +            = {CustomEntityNotFoundException.class, CustomFailedToDeleteEntityException.class})
What if an entity cannot be removed due to some constraints? (e.g. it is a part of FR for some third entitty)

2021-06-03 10:39 UTC, jules-n approved these changes
Good job

2021-06-03 10:41 UTC, nelfan approved these changes
+1

2021-06-03 10:52 UTC, Dchad99 commented on controller/src/main/java/com/softserve/borda/config/jwt/JwtConvertor.java
>      }
You may use @AllArgsConstructor

2021-06-03 11:06 UTC, merged