Add a check for the existence of a user by username to registerUser
nelfan/BORDA pull request #52
Opened 2021-06-11 14:06 UTC by nelfan

https://trello.com/c/1IuyjIDD/207-add-checking-user-existing-by-username-in-back-end-validation

2021-06-11 14:58 UTC, ChernykhVyacheslav approved these changes
Looks good!

2021-06-11 16:03 UTC, achehrynets requested changes
Requested changes

2021-06-11 16:03 UTC, achehrynets commented on controller/src/main/java/com/softserve/borda/controllers/AuthController.java
> +            throw new CustomAuthenticationFailedException("Username: [" + registrationRequest.getUsername() + "] is already taken");
I think, it is better to just return bad request status with detailed message here rather than throw exception.

2021-06-13 20:44 UTC, jules-n approved these changes
Looks fine

2021-06-14 16:08 UTC, AButrym approved these changes
Looks good

2021-06-21 11:58 UTC, merged